# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - master

pool:
    vmImage: 'ubuntu-latest'

stages:
    - stage: A
      jobs:
          - job:
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSpec: '10.x'
                  displayName: 'Install Node.js'

                - script: npm install
                  workingDirectory: client
                  displayName: 'npm install'

                - script: npm run build
                  workingDirectory: client
                  displayName: 'npm run build'

    - stage: B
      dependsOn: A
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
      jobs:
          - job:
            steps:
                - script: |
                      git ftp catchup
                      git ftp push -s production --all
                  displayName: 'Pushing FTP packages...'
